### ISSUE TITLE
Adding a README.md file with a screenshot?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [agronick/Relay#1]
Could you add a `README.md` file where you will write a short description to your project and provide us with a screenshot of the interface? That would be much helpful.

**Comment by agronick** [comment]
I'll definitely add one once it is usable.

**Comment by agronick** [comment]
The problem is with automake. It will complain if it does not have a README file. I tried messing with the automake files to make that error but I can't really do it without symlinking it.
