### ISSUE TITLE
Relay should use svg icons for appicon and buttons

### ISSUE THREAD

**Issue by quassy** [agronick/Relay#10]
Currently the assets and the appicon of Relay itself are `.png` files. Icons for the interface should be svg so Relay is ready for hidpi mode, the appicon itself should be svg (in multiple sizes) so it does not appear blurry (atm it's quite blurry in Plank).

**Comment by agronick** [comment]
I'll see what I can do with this. There is a subtle starburst behind the icon but it might get washed out and be unnoticeable anyways. I added the Gimp source file to the root as relay_icon.xcf if you want to try doing something with it.

Any other icons came from http://iconfinder.com and they'll need to be converted manually. There are a few that come from the current GTK theme and they will use whatever you have on your computer already.

**Comment by agronick** [comment]
I tried doing it in inkscape but I can't get anything close in the amount of colors to import. Maybe if the images were preresized plank wouldn't need to do the resizing.

**Comment by bil-elmoussaoui** [comment]
elementaryPlus might help you creating a new svg application icon, [more info](https://github.com/mank319/elementaryPlus/issues/252)

**Comment by quassy** [comment]
I think your SVG file might be broken, it's also not properly displayed in GitHub. [Might wanna try it with my first iteration of the Relay icon.](https://github.com/mank319/elementaryPlus/blob/add-relay/elementaryPlus/apps/128/relay.svg)

**Comment by agronick** [comment]
That looks really nice. I'll use it.

**Comment by agronick** [comment]
One issue, it needs to be trimmed. It looks smaller than the other icons.

**Comment by quassy** [comment]
If you display it at 128px (e.g. in Slingshot) it should be pretty much the same size as most (/ all square) elementary icons. I will make smaller versions too (64, 48, 32, 24, 16), then Relay will fit in with the other apps in Plank (which uses 48px afaik).

**Comment by agronick** [comment]
You don't think to make smaller versions unless they are different. I don't know where a smaller icon would be needed anyways. Its an SVG and its in the scaled folder so it will scale.

I just made it a little bigger and it looks the same size as the other icons. Thanks for doing that. It looks great.

**Comment by quassy** [comment]
Quoting Daniel Foré: 

> However, keep in mind that while SVGs are Scalable, they aren't inherently Resizable. We still need different canvas sizes within the same scale to get the sharpest looking icons.

Smaller versions of icons are different, as they still have 1px lines for highlight / contrast and use simpler shapes, less detail to still be sharp and easily recognisable. This is why elementary (and many other icon packs) ship different icon sizes even though they use svg. From the top of my mind an icon can appear in Slingshot (huge), Plank (medium), Multitasking Overview (small) and Files (depends on view setting).

**Comment by agronick** [comment]
Ok thats fine. If you want to make them I'll put them in.
