### ISSUE TITLE
[UI] Add right click context menu to pre-existing server list

### ISSUE THREAD

**Issue by rodneyrod** [agronick/Relay#14]
Currently the only way to connect to an existing listed server is to double click on the entry, where most clients use *right click* - 'Connect' or something similar. Adding a right click context menu to the server entries should help make the client more intuitive for users coming from other platforms.

**Comment by agronick** [comment]
Don't know if this is possible with the methods in that widget. I'll make sure.

**Comment by agronick** [comment]
It now connects on single click
