### ISSUE TITLE
[UI] Add UI Appearance preferences

### ISSUE THREAD

**Issue by rodneyrod** [agronick/Relay#15]
KyRC's default channel window (for me) selects white as both the default background and text colour, although my username colour is changed.
Adding preferences to change these settings should be included in a future version.

**Comment by agronick** [comment]
Are you using Ubuntu? I just put in a fix for Ubuntu. Let me know what distro you are using and we'll figure out how to detect it.

**Comment by rodneyrod** [comment]
Yeah, Ubuntu Studio with Xfce 4.12

**Comment by agronick** [comment]
Can you run `echo $XDG_CURRENT_DESKTOP` in a command line and tell me what it outputs? Right now it is set to detect Unity which is sounds like you won't have. And if you type in `locate Adwaita` in a command line do you get a bunch of results?

**Comment by rodneyrod** [comment]
Yeah, text still missing, although it's changed to a very slightly off white colour, same as before.
The XDG command returns 'XFCE' (no quotes).
Yes, do get a lot of results when typing 'locate Adwaita'

**Comment by agronick** [comment]
Ok its should be dark now. Its uploaded.

**Comment by rodneyrod** [comment]
All fixed, the fastest I've ever seen something done on Github :)
Thanks.
