### ISSUE TITLE
Add a line to show where I left off

### ISSUE THREAD

**Issue by pizzamaker** [agronick/Relay#18]
It would be nice to see a line showing you where you left off the conversation the last time Relay was the application on focus. Kinda like what Pidgin does.

Keep up the great work! :)

**Comment by pizzamaker** [comment]
Perhaps a low-contrast dotted line would look good?

**Comment by agronick** [comment]
Yeah thats a really good idea but I think there should be like a 1 minute timeout before drawing the lines because if you're switching tabs a lot you'll have lines everywhere.

**Comment by quassy** [comment]
Just move the line to the bottom of the conversation once the user leaves the tab again. So there is only one line which shows what has happened since one last had the tab open.

**Comment by pizzamaker** [comment]
@agronick yeah @quassy is right

**Comment by agronick** [comment]
Alright that makes sense.

**Comment by agronick** [comment]
@quassy and @pizzamaker Do you like it? Is it what you wanted?

**Comment by pizzamaker** [comment]
ATM I can't test it as I'm on Trisquel and the program failed to build here. Here's hoping the PPA comes back up :)

**Comment by agronick** [comment]
What fails to build? Can you open up a bug for it with the output?

**Comment by pizzamaker** [comment]
Sure!

**Comment by pizzamaker** [comment]
I'm not sure if it's worth opening a bug for it though, the only issue so far is that package valac-0.26 can't be found in the Trisquel repository. Is there a workaround?

**Comment by agronick** [comment]
You can just install an older version. I don't even think you need to 
change any files.
