### ISSUE TITLE
Consider changing "ElementaryOS" to "elementary OS"

### ISSUE THREAD

**Issue by aleksandar-todorovic** [agronick/Relay#2]
For the consistency, it would be useful to change the string `ElementaryOS` to `elementary OS`.

The name of this distribution should always be spelled like that, with a lowercase `e` and a blank space between those two words.

I found this in the project's description, but you have might made the same mistake somewhere in the code as well.

**Comment by agronick** [comment]
The only place it appears is in the description on Github. I just grepped the whole project. I just searched "Ubuntu" on Github and it is capitalized whenever it is mentioned in a description.  Who says the distro name needs to be in lowercase?

**Comment by aleksandar-todorovic** [comment]
I know that's the case in Ubuntu, however elementary's main developers prefer referring to the system using lowercase `e` and diving the world `elementary` from the word `OS` with a blank space.

> #### Internal Branding Guidelines

> elementary has two logos: a logotype (stylized “elementary”) and a logomark (stylized “e”). Use one or the other when referencing elementary itself or products created by elementary (elementary OS, the elementary icons, etc.). The logos should not be used together (use one or the other), when referring to a third-party product, if modified (stretched, colorized, or otherwise altered), or on a busy background.

> The word “elementary” should be used when referring to the overarching project. “elementary OS” is a product of elementary. The “e” should always be written in lowercase. Don’t use “eOS” as an abbreviation for elementary OS; it sounds a lot like a certain fruity operating system and reminds us of the “KThis” and “GThat” trend.

[Source](http://blog.elementary.io/post/107640994166/the-importance-of-our-brand)

**Comment by agronick** [comment]
I grepped the whole source. Where is it?
