### ISSUE TITLE
Tab Auto-complete nickname

### ISSUE THREAD

**Issue by Hippyjake** [agronick/Relay#22]
Not sure if this is planed or not: But its a great feature for those of us with lazy fingers.

Works great on ArchLinux!

**Comment by agronick** [comment]
Thats great that it works on arch. Would you mind giving me 
instructions for what you did to install it so I can put it in the 
readme?

**Comment by agronick** [comment]
BTW I'm 90% sure I'll implement that once everything else is done.

**Comment by Hippyjake** [comment]
I had to install vala (0.28.0-1) and granite (0.3.0-1) both are in the regular repo. I had every thing installed. Im glad to see it builds on newer versions of the libs. Your build instructions work just fine.
