### ISSUE TITLE
Two issues on Ubuntu 15.04

### ISSUE THREAD

**Issue by PandaJim** [agronick/Relay#25]
Hey, this IRC client looks really good and I just tried it on Ubuntu 15.04 (0.2 version from the PPA) and found 2 issues:

1. on the default Unity desktop, ONCE I click the Relay icon on left Launcher to minimize the window session crashes (bring me back to the login screen) immediately.

2. on Gnome Shell, there's a display (or maybe font) issue, see picture:

![relay-irc-gnome](https://cloud.githubusercontent.com/assets/6194441/8934777/e0d0640c-357b-11e5-9858-ac65a458a5c1.jpg)

**Comment by agronick** [comment]
Yeah, the minimize issue has been a big pain. Its got to be something with Compiz. No other desktop crashes. I've filed a bug with Compiz. For me it was only crashing with sqare buttons. Circular buttons like the ones in your screenshot weren't causing issues. When this happens there is no error with Relay. It doesn't crash or segfault. I spent a lot of time trying to debug this until I realized it wasn't Relay.

It should be settings everything to use a dark theme. There is some code to use the Adwaita theme on Ubuntu. Do you have it? Relay looks a lot better with a dark theme. It seems for you it didn't switch. If you echo $XDG_CURRENT_DESKTOP and it equals "Unity" and /usr/share/themes/Adwaita exists it should use the Adwaita theme.

However if you are still on a light theme it shouldn't be showing those colors. There is some code to obtain the luma of the window and judge if you are on a dark or light theme and set the colors accordingly. It seems that something is preventing this from happening.

**Comment by agronick** [comment]
Ok the colors being wrong should be fixed
