### ISSUE TITLE
Unable to compile package

### ISSUE THREAD

**Issue by rodneyrod** [agronick/Relay#3]
Autogen.sh gives me the following message:
```
**Error**: Directory `.' does not look like the top-level package directory
```
By looking at the script, it seems as though it can't find a file called configure.ac, which isn't in the git branch.
Just using make doesn't work inside the src directory either.

**Comment by rodneyrod** [comment]
Running autogen.sh and make from the top directory currently doesn't work, and running make in the /src directory returns the following error:
```
.deps/kyrc.Po:1: *** missing separator (did you mean TAB instead of 8 spaces?). Stop.
```

**Comment by agronick** [comment]
I'll try to compile it by itself. I haven't considered that anyone 
would want to run it. It is getting more and more stable though. For 
right now I was just using Github as a backup.

**Comment by rodneyrod** [comment]
@agronick This is the only IRC client (AFAIK) built on GTK that isn't inspired by XChat and doesn't pull in empathy or a whole swathe of libraries like Smuxie does, so for me it fills a niche, and I'd be very happy to help you bug test this.
Also no pressure, from what I've seen it looks like you're doing a good job with the code so far.

**Comment by agronick** [comment]
It should compile now with
./autogen.sh
make

You can then run it in src/kyrc. I wouldn't install it yet because it should just be tested right now and I haven't gone over the installation scripts.

By the way it is very light weight. It uses about 6mb of RAM. I definitely appreciate the help testing.

**Comment by agronick** [comment]
Does it work now?

**Comment by rodneyrod** [comment]
Yep, works fine. I'll run some tests on the latest revision when I get home tonight.

Thanks for fixing this :+1:
