### ISSUE TITLE
Blank tabs

### ISSUE THREAD

**Issue by kerunaru** [agronick/Relay#34]
After fixing #33, now I can use Relay but I only get blank tabs... The one I can actually see is the server log tab (with strange unicode characters, btw...)

![screenshot](https://cloud.githubusercontent.com/assets/94023/11607368/05da6d32-9b44-11e5-8715-d8ccb4570887.png)

:(

**Comment by agronick** [comment]
Does this happen every time you start it? I Can you tell me what channels and servers you are connecting to so I can see if I can recreate it?

It probably has something to do with removing the code that filtered out special characters.

**Comment by kerunaru** [comment]
Yes, this is happening everytime I start Relay. I connect to irc.freenode.org, you can pick whatever channel you want, it happens to me in all of them.

The thing is the server log tab is fine (except for special characters)

![captura de pantalla de 2015-12-13 13 12 39](https://cloud.githubusercontent.com/assets/94023/11766914/4b56dae6-a19b-11e5-8828-6d5143e9ef90.png)

**Comment by agronick** [comment]
I need to put that regex back in but to keep a certain range of characters.

**Comment by agronick** [comment]
Are you still seeing this issue? Its working fine for me.

**Comment by kerunaru** [comment]
Nope. I'll close this for you. Thanks! :dancer:
